name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8
        ports: ['3306:3306']
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: coin_chest_test
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '13'
    - name: Run a one-line script
      run: ./gradlew test
      env:
        SPRING_DATASOURCE_URL: 'jdbc:mysql://localhost:3306/coin_chest_test?rewriteBatchedStatements=true'
